/**
 * Task #312 integration tests: every audit-log event that fires alongside a
 * `buildPromptLegInputs`-derived Claude prompt must carry the three
 * traceability counters (`hasPerLegContext`, `perLegContextLegCount`,
 * `siblingDuplicateCount`) so we can answer "did the AI see the per-leg
 * finding when it drafted this?" from the audit log alone.
 *
 * Four prompt sites → four audited events:
 *   - portal_understanding_preflight  (POST /portal-submissions/preflight-understanding)
 *   - portal_draft_created            (POST /portal-submissions/generate-preview)
 *   - portal_draft_regenerated        (POST /portal-submissions/:id/regenerate)
 *   - email_generated                 (POST /claims/:id/generate-email)
 *
 * The Anthropic SDK is stubbed via `__setAnthropicClientForTesting` so we
 * can exercise real route handlers end-to-end without provisioning
 * credentials. Each test seeds a fresh invoice group with a primary leg
 * (per_leg_context set) and a sibling duplicate, so the helper produces
 * non-zero counters and the assertions can pin all three values.
 */

import { test, before, after } from "node:test";
import { strict as assert } from "node:assert";
import http from "node:http";
import express, { type Express, type Request, type Response, type NextFunction } from "express";
import { eq, and } from "drizzle-orm";

import portalSubmissionsRouter from "../routes/portal-submissions";
import invoiceGroupsRouter from "../routes/invoice-groups";
import aiEmailRouter from "../routes/ai-email";
import {
  db,
  pool,
  claimsTable,
  invoiceGroupsTable,
  auditLogsTable,
  notesTable,
  portalSubmissionsTable,
  claimEvidenceTable,
  stateEventsTable,
  errorTypesTable,
} from "@workspace/db";
import { __setAnthropicClientForTesting } from "@workspace/integrations-anthropic-ai";

let server: http.Server;
let baseUrl: string;

const TEST_USER = { email: "task-312-tester@example.com", displayName: "Task #312 Tester" };

// ---------------------------------------------------------------------------
// Anthropic stub — returns canned text for every call. The route handlers
// only care that `messages.create` returns a valid shape; this stub keeps
// the LLM out of the loop entirely.
// ---------------------------------------------------------------------------

function makeAnthropicStub() {
  return {
    messages: {
      async create(_args: unknown): Promise<{ content: Array<{ type: string; text: string }> }> {
        // The per-claim email handler expects JSON in the body; the portal
        // description handler expects free text; the readback handler
        // expects free text. A JSON payload satisfies the email parser
        // (which JSON.parses the text) and the other two consumers just
        // trim/store the text — so a single JSON-shaped reply works for
        // all sites.
        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              subject: "Test dispute subject",
              body: "Test dispute body — generated by Task #312 stub.",
            }),
          }],
        };
      },
    },
  };
}

before(async () => {
  // Stub the Anthropic SDK so route handlers don't need real credentials.
  __setAnthropicClientForTesting(makeAnthropicStub() as never);

  const app: Express = express();
  app.use(express.json());

  app.use((req: Request, _res: Response, next: NextFunction) => {
    (req as { user?: typeof TEST_USER & { status: string }; isAuthenticated?: () => boolean; log?: unknown }).user = { ...TEST_USER, status: "approved" };
    (req as { isAuthenticated?: () => boolean }).isAuthenticated = () => true;
    (req as { log?: unknown }).log = { error: () => {}, warn: () => {}, info: () => {}, debug: () => {} };
    next();
  });

  app.use("/api", portalSubmissionsRouter);
  app.use("/api", invoiceGroupsRouter);
  app.use("/api", aiEmailRouter);

  await new Promise<void>((resolveListen, rejectListen) => {
    server = app.listen(0, () => {
      const addr = server.address();
      if (typeof addr === "object" && addr) {
        baseUrl = `http://127.0.0.1:${addr.port}`;
        resolveListen();
      } else {
        rejectListen(new Error("Failed to obtain test server port"));
      }
    });
  });
});

after(async () => {
  __setAnthropicClientForTesting(null);
  server.closeAllConnections?.();
  await new Promise<void>((resolveClose) => server.close(() => resolveClose()));
  await pool.end().catch(() => undefined);
});

// ---------------------------------------------------------------------------
// HTTP helper
// ---------------------------------------------------------------------------

async function fetchJson<T = unknown>(
  path: string,
  init?: { method?: string; body?: unknown },
): Promise<{ status: number; json: T }> {
  const url = new URL(`${baseUrl}${path}`);
  return new Promise((resolveReq, rejectReq) => {
    const body = init?.body !== undefined ? JSON.stringify(init.body) : undefined;
    const headers: Record<string, string> = {};
    if (body) {
      headers["Content-Type"] = "application/json";
      headers["Content-Length"] = Buffer.byteLength(body).toString();
    }
    const req = http.request(
      {
        hostname: url.hostname,
        port: url.port,
        path: url.pathname + url.search,
        method: init?.method ?? "GET",
        headers,
      },
      (res) => {
        let raw = "";
        res.setEncoding("utf8");
        res.on("data", (c) => { raw += c; });
        res.on("end", () => {
          try {
            resolveReq({ status: res.statusCode ?? 0, json: raw ? JSON.parse(raw) : ({} as T) });
          } catch (e) { rejectReq(e); }
        });
      },
    );
    req.on("error", rejectReq);
    if (body) req.write(body);
    req.end();
  });
}

// ---------------------------------------------------------------------------
// Seed helpers — each test owns its group + cleanup so they don't interfere.
// ---------------------------------------------------------------------------

interface SeedHandle {
  groupId: number;
  primaryClaimId: number;
  duplicateClaimId: number;
  errorTypeId: number;
}

async function seedGroupWithPerLegContextAndSibling(): Promise<SeedHandle> {
  const suffix = `${Date.now()}-${Math.floor(Math.random() * 1e6)}`;

  const [errType] = await db.insert(errorTypesTable).values({
    name: `T312-ErrType-${suffix}`,
    description: "Trip distance mismatch",
    guidance: "Verify GPS breadcrumbs.",
    decisionTree: null,
  }).returning();

  const [group] = await db.insert(invoiceGroupsTable).values({
    invoiceNumber: `T312-INV-${suffix}`,
    status: "Needs Evidence",
    outcome: "Pending",
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    errorDetails: "Distance billed exceeds the contract distance for this leg.",
  }).returning();

  // Primary leg: has per_leg_context (drives perLegContextLegCount=1).
  const [primary] = await db.insert(claimsTable).values({
    confNumber: `T312-PRI-${suffix}`,
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    status: "Needs Evidence",
    outcome: "Pending",
    sopOutcome: "portal_dispute",
    includedInDispute: true,
    claimAmount: "42.50",
    date: "2026-01-15",
    clientNumber: "C100",
    carNumber: "CAR-7",
    perLegContext: "Driver waited 47 minutes; member confirmed delay.",
  }).returning();

  // Sibling duplicate rolled under the primary
  // (drives siblingDuplicateCount=1 on the primary's slice).
  const [duplicate] = await db.insert(claimsTable).values({
    confNumber: `T312-DUP-${suffix}`,
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    status: "Needs Evidence",
    outcome: "Pending",
    sopOutcome: "portal_dispute",
    includedInDispute: true,
    claimAmount: "55.00",
    date: "2026-01-16",
    clientNumber: "C100",
    carNumber: "CAR-7",
    duplicateOfClaimId: primary.id,
  }).returning();

  return {
    groupId: group.id,
    primaryClaimId: primary.id,
    duplicateClaimId: duplicate.id,
    errorTypeId: errType.id,
  };
}

async function cleanupSeed(seed: SeedHandle): Promise<void> {
  await db.delete(stateEventsTable).where(eq(stateEventsTable.invoiceGroupId, seed.groupId)).catch(() => undefined);
  await db.delete(portalSubmissionsTable).where(eq(portalSubmissionsTable.invoiceGroupId, seed.groupId)).catch(() => undefined);
  await db.delete(auditLogsTable).where(eq(auditLogsTable.invoiceGroupId, seed.groupId)).catch(() => undefined);
  for (const id of [seed.primaryClaimId, seed.duplicateClaimId]) {
    await db.delete(stateEventsTable).where(eq(stateEventsTable.claimId, id)).catch(() => undefined);
    await db.delete(auditLogsTable).where(eq(auditLogsTable.claimId, id)).catch(() => undefined);
    await db.delete(notesTable).where(eq(notesTable.claimId, id)).catch(() => undefined);
    await db.delete(claimEvidenceTable).where(eq(claimEvidenceTable.claimId, id)).catch(() => undefined);
    await db.delete(claimsTable).where(eq(claimsTable.id, id)).catch(() => undefined);
  }
  await db.delete(claimEvidenceTable).where(eq(claimEvidenceTable.invoiceGroupId, seed.groupId)).catch(() => undefined);
  await db.delete(invoiceGroupsTable).where(eq(invoiceGroupsTable.id, seed.groupId)).catch(() => undefined);
  await db.delete(errorTypesTable).where(eq(errorTypesTable.id, seed.errorTypeId)).catch(() => undefined);
}

/**
 * Pull the latest audit row for `(groupId, action)` and return its
 * metadata. Asserts a single matching row exists so we don't silently
 * miss duplicates from earlier-stored runs (cleanup happens in `finally`,
 * but a fresh group per test makes this a tight invariant).
 */
async function latestAuditMetadata(opts: {
  groupId?: number;
  claimId?: number;
  action: string;
}): Promise<Record<string, unknown>> {
  const conditions = [eq(auditLogsTable.action, opts.action)];
  if (opts.groupId !== undefined) conditions.push(eq(auditLogsTable.invoiceGroupId, opts.groupId));
  if (opts.claimId !== undefined) conditions.push(eq(auditLogsTable.claimId, opts.claimId));
  const rows = await db.select().from(auditLogsTable).where(and(...conditions));
  assert.equal(rows.length, 1, `expected exactly one '${opts.action}' audit row, found ${rows.length}`);
  const meta = rows[0].metadata;
  assert.ok(meta && typeof meta === "object", `'${opts.action}' audit row has no metadata`);
  return meta as Record<string, unknown>;
}

/**
 * Shared assertion: every audited prompt site must surface the three
 * traceability counters. Asserting on exact key presence catches a key
 * being renamed or omitted; asserting on values catches a routing bug
 * where the wrong `promptLegInputs` was threaded into the metadata.
 */
function assertCountersPresent(meta: Record<string, unknown>, expected: {
  hasPerLegContext: boolean;
  perLegContextLegCount: number;
  siblingDuplicateCount: number;
}): void {
  assert.ok(Object.prototype.hasOwnProperty.call(meta, "hasPerLegContext"), "metadata missing hasPerLegContext");
  assert.ok(Object.prototype.hasOwnProperty.call(meta, "perLegContextLegCount"), "metadata missing perLegContextLegCount");
  assert.ok(Object.prototype.hasOwnProperty.call(meta, "siblingDuplicateCount"), "metadata missing siblingDuplicateCount");
  assert.equal(meta.hasPerLegContext, expected.hasPerLegContext);
  assert.equal(meta.perLegContextLegCount, expected.perLegContextLegCount);
  assert.equal(meta.siblingDuplicateCount, expected.siblingDuplicateCount);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test("portal_understanding_preflight audit row includes per-leg counters", async () => {
  const seed = await seedGroupWithPerLegContextAndSibling();
  try {
    const res = await fetchJson("/api/portal-submissions/preflight-understanding", {
      method: "POST",
      body: { invoiceGroupId: seed.groupId, disputeReason: "Mileage mismatch", specialCircumstances: "" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);

    const meta = await latestAuditMetadata({ groupId: seed.groupId, action: "portal_understanding_preflight" });
    // Primary has per_leg_context (count=1) + 1 sibling duplicate rolled under it.
    assertCountersPresent(meta, {
      hasPerLegContext: true,
      perLegContextLegCount: 1,
      siblingDuplicateCount: 1,
    });
  } finally {
    await cleanupSeed(seed);
  }
});

// Task #703: per-leg counters formerly carried by the
// `portal_draft_created` audit (which fired alongside a ghost
// `portal_submissions` row inserted on every Generate-preview click)
// are now carried on the `group_preview_generated` audit on the
// invoice-group's timeline. The Generate-preview UI flow calls
// `/invoice-groups/:id/preview-generated`, not the legacy
// `/portal-submissions/generate-preview` route.
test("group_preview_generated audit row includes per-leg counters (Task #703)", async () => {
  const seed = await seedGroupWithPerLegContextAndSibling();
  try {
    const res = await fetchJson(`/api/invoice-groups/${seed.groupId}/preview-generated`, {
      method: "POST",
      body: {},
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);

    const meta = await latestAuditMetadata({ groupId: seed.groupId, action: "group_preview_generated" });
    assertCountersPresent(meta, {
      hasPerLegContext: true,
      perLegContextLegCount: 1,
      siblingDuplicateCount: 1,
    });

    // Task #703 regression: the route must NOT insert a ghost
    // `portal_submissions` row alongside the generated text. Pre-#703
    // every preview click silently created a status='draft' row that
    // leaked into the Portal Submissions list/queue/drawer.
    const ghostRows = await db.select({ id: portalSubmissionsTable.id })
      .from(portalSubmissionsTable)
      .where(eq(portalSubmissionsTable.invoiceGroupId, seed.groupId));
    assert.equal(ghostRows.length, 0, `expected 0 portal_submissions rows after preview, found ${ghostRows.length}`);
  } finally {
    await cleanupSeed(seed);
  }
});

// Task #703: same migration for the regenerate path. The Regenerate-
// from-preview UI button calls `/invoice-groups/:id/draft/regenerate`,
// which now stamps per-leg counters onto the
// `group_draft_regenerated` audit (formerly carried by the
// `portal_draft_regenerated` audit on the ghost row). The remaining
// `portal_draft_regenerated` audit is now only emitted by the drawer's
// post-submit regenerate path (POST /portal-submissions/:id/regenerate)
// against an already-existing real row, not on preview.
test("group_draft_regenerated audit row includes per-leg counters (Task #703)", async () => {
  const seed = await seedGroupWithPerLegContextAndSibling();
  try {
    // Step 1: stamp the initial preview so the group has draft text on file.
    const preview = await fetchJson(`/api/invoice-groups/${seed.groupId}/preview-generated`, {
      method: "POST",
      body: {},
    });
    assert.equal(preview.status, 200, `preview failed: ${JSON.stringify(preview.json)}`);

    // Step 2: regenerate the draft.
    const regen = await fetchJson(`/api/invoice-groups/${seed.groupId}/draft/regenerate`, {
      method: "POST",
      body: {},
    });
    assert.equal(regen.status, 200, `regenerate failed: ${regen.status} ${JSON.stringify(regen.json)}`);

    const meta = await latestAuditMetadata({ groupId: seed.groupId, action: "group_draft_regenerated" });
    assertCountersPresent(meta, {
      hasPerLegContext: true,
      perLegContextLegCount: 1,
      siblingDuplicateCount: 1,
    });

    // Task #703 regression: still no ghost portal_submissions rows
    // after preview + regenerate.
    const ghostRows = await db.select({ id: portalSubmissionsTable.id })
      .from(portalSubmissionsTable)
      .where(eq(portalSubmissionsTable.invoiceGroupId, seed.groupId));
    assert.equal(ghostRows.length, 0, `expected 0 portal_submissions rows after preview+regenerate, found ${ghostRows.length}`);
  } finally {
    await cleanupSeed(seed);
  }
});

test("email_generated audit row (per-claim email path) includes per-leg counters for the primary slice", async () => {
  const seed = await seedGroupWithPerLegContextAndSibling();
  try {
    const res = await fetchJson(`/api/claims/${seed.primaryClaimId}/generate-email`, {
      method: "POST",
      body: { disputeReason: "GPS shows shorter distance than billed" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);

    const meta = await latestAuditMetadata({ claimId: seed.primaryClaimId, action: "email_generated" });
    // Per-claim email path passes `legs: [primary]`, `groupLegs:
    // [primary, duplicate]` — primary owns the finding (perLegContext=1)
    // and lists the sibling duplicate (siblingDuplicateCount=1).
    assertCountersPresent(meta, {
      hasPerLegContext: true,
      perLegContextLegCount: 1,
      siblingDuplicateCount: 1,
    });
    // Sanity: we also retain the existing `generationMethod` field added
    // alongside the counters.
    assert.ok(meta.generationMethod === "llm" || meta.generationMethod === "template");
  } finally {
    await cleanupSeed(seed);
  }
});

test("email_generated audit row (per-claim email path) for a duplicate slice — counters reflect the slice (no per-leg context)", async () => {
  const seed = await seedGroupWithPerLegContextAndSibling();
  try {
    const res = await fetchJson(`/api/claims/${seed.duplicateClaimId}/generate-email`, {
      method: "POST",
      body: { disputeReason: "Duplicate of primary" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);

    const meta = await latestAuditMetadata({ claimId: seed.duplicateClaimId, action: "email_generated" });
    // Duplicate-only slice: helper suppresses the per-leg context (primary
    // owns the finding) and sibling refs only accrue on primaries — so
    // both counts read 0 even though the underlying group has both. This
    // is the correct projection: the slice is what the prompt actually
    // sees.
    assertCountersPresent(meta, {
      hasPerLegContext: false,
      perLegContextLegCount: 0,
      siblingDuplicateCount: 0,
    });
  } finally {
    await cleanupSeed(seed);
  }
});
