// Per-leg state-machine endpoint tests for Task #196.
//
// Each test exercises one of the 11 contract endpoints end-to-end through
// a real Express server bound to the live database. The tests focus on:
//
//   • Source-state contract enforcement (409 + { error, expectedState,
//     actualState } body shape).
//   • Discrete-column writes landing in the right places.
//   • audit_logs and state_events rows being inserted with the agreed
//     action / event_key vocabulary.
//   • Cross-resource side effects: classify → renormalized fields,
//     verdict → MAS-derivation, group reattest/complete → attestation
//     gate engagement.
//
// Harness mirrors `attestation.test.ts` so the cleanup pattern stays
// consistent across the task suite.

import { test, before, after } from "node:test";
import { strict as assert } from "node:assert";
import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import express, { type Express, type Request, type Response, type NextFunction } from "express";
import { eq, and, desc, inArray } from "drizzle-orm";

import claimsRouter from "../routes/claims";
import invoiceGroupsRouter from "../routes/invoice-groups";
import importRouter from "../routes/import";
import {
  db,
  pool,
  claimsTable,
  invoiceGroupsTable,
  auditLogsTable,
  notesTable,
  portalResponsesTable,
  portalSubmissionsTable,
  claimEvidenceTable,
  claimVerdictTable,
  errorTypesTable,
  stateEventsTable,
} from "@workspace/db";
import { __setAnthropicClientForTesting } from "@workspace/integrations-anthropic-ai";

let server: http.Server;
let baseUrl: string;

const TEST_USER = { email: "per-leg-tester@example.com", displayName: "Per-Leg Tester" };

// Anthropic stub — `/invoice-groups/:id/preview-generated` and
// `/invoice-groups/:id/draft/regenerate` now run the LLM pipeline so
// every preview-flow test in this file needs the SDK stubbed. The
// canned JSON-shaped response satisfies both the portal description
// consumer (free text) and the per-claim email consumer (JSON.parse).
function makeAnthropicStub() {
  return {
    messages: {
      async create(_args: unknown): Promise<{ content: Array<{ type: string; text: string }> }> {
        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              subject: "Test dispute subject",
              body: "Test dispute body — generated by per-leg-state stub.",
            }),
          }],
        };
      },
    },
  };
}

before(async () => {
  __setAnthropicClientForTesting(makeAnthropicStub() as never);
  const app: Express = express();
  app.use(express.json());

  app.use((req: Request, _res: Response, next: NextFunction) => {
    (req as any).user = { ...TEST_USER, status: "approved" };
    (req as any).isAuthenticated = () => true;
    (req as any).log = { error: () => {}, warn: () => {}, info: () => {}, debug: () => {} };
    next();
  });

  app.use("/api", claimsRouter);
  app.use("/api", invoiceGroupsRouter);
  app.use("/api", importRouter);

  await new Promise<void>((resolveListen, rejectListen) => {
    server = app.listen(0, () => {
      const addr = server.address();
      if (typeof addr === "object" && addr) {
        baseUrl = `http://127.0.0.1:${addr.port}`;
        resolveListen();
      } else {
        rejectListen(new Error("Failed to obtain test server port"));
      }
    });
  });
});

after(async () => {
  __setAnthropicClientForTesting(null);
  server.closeAllConnections?.();
  await new Promise<void>((resolveClose) => server.close(() => resolveClose()));
  await pool.end().catch(() => undefined);
});

async function fetchJson<T = any>(
  path: string,
  init?: { method?: string; body?: unknown },
): Promise<{ status: number; json: T }> {
  const url = new URL(`${baseUrl}${path}`);
  return new Promise((resolveReq, rejectReq) => {
    const body = init?.body !== undefined ? JSON.stringify(init.body) : undefined;
    const req = http.request(
      {
        hostname: url.hostname,
        port: url.port,
        path: url.pathname + url.search,
        method: init?.method ?? "GET",
        headers: body
          ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body).toString() }
          : {},
      },
      (res) => {
        let raw = "";
        res.setEncoding("utf8");
        res.on("data", (c) => { raw += c; });
        res.on("end", () => {
          try {
            resolveReq({ status: res.statusCode ?? 0, json: raw ? JSON.parse(raw) : ({} as T) });
          } catch (e) { rejectReq(e); }
        });
      },
    );
    req.on("error", rejectReq);
    if (body) req.write(body);
    req.end();
  });
}

// --- Seeding ------------------------------------------------------------
import { phaseForStatus, dispositionForGroup } from "./fixtures/state";

async function createSeedGroup(opts: { status?: any; phase?: any } = {}): Promise<typeof invoiceGroupsTable.$inferSelect> {
  const invoiceNumber = `T196G-${Date.now()}-${Math.floor(Math.random() * 1e6)}`;
  const status = opts.status ?? "Needs Evidence";
  const [row] = await db.insert(invoiceGroupsTable).values({
    invoiceNumber,
    status,
    outcome: "Pending",
    phase: opts.phase ?? phaseForStatus(status),
  }).returning();
  return row;
}

async function createSeedClaim(opts: {
  invoiceGroupId?: number | null;
  errorTypeId?: string | null;
  errorTypeName?: string | null;
  sopOutcome?: string | null;
  holdReason?: string | null;
  status?: any;
  outcome?: any;
  includedInDispute?: boolean;
} = {}): Promise<typeof claimsTable.$inferSelect> {
  const confNumber = `T196-${Date.now()}-${Math.floor(Math.random() * 1e6)}`;
  const invoiceGroupId = opts.invoiceGroupId ?? null;
  const disposition = await dispositionForGroup(invoiceGroupId);
  const [row] = await db.insert(claimsTable).values({
    confNumber,
    status: opts.status ?? "Needs Evidence",
    outcome: opts.outcome ?? "Pending",
    invoiceGroupId,
    errorTypeId: Object.prototype.hasOwnProperty.call(opts, "errorTypeId") ? opts.errorTypeId : null,
    errorTypeName: opts.errorTypeName ?? null,
    sopOutcome: opts.sopOutcome ?? null,
    holdReason: opts.holdReason ?? null,
    includedInDispute: opts.includedInDispute ?? true,
    claimAmount: "100.00",
    disposition,
  }).returning();
  return row;
}

async function createSeedErrorType(tree?: any): Promise<typeof errorTypesTable.$inferSelect> {
  const name = `T196-ErrType-${Date.now()}-${Math.floor(Math.random() * 1e6)}`;
  const [row] = await db.insert(errorTypesTable).values({
    name,
    description: "test",
    decisionTree: tree ?? null,
  }).returning();
  return row;
}

async function cleanupClaim(id: number) {
  await db.delete(claimVerdictTable).where(eq(claimVerdictTable.claimId, id)).catch(() => undefined);
  await db.delete(stateEventsTable).where(eq(stateEventsTable.claimId, id)).catch(() => undefined);
  await db.delete(portalResponsesTable).where(eq(portalResponsesTable.claimId, id)).catch(() => undefined);
  await db.delete(auditLogsTable).where(eq(auditLogsTable.claimId, id)).catch(() => undefined);
  await db.delete(notesTable).where(eq(notesTable.claimId, id)).catch(() => undefined);
  await db.delete(claimEvidenceTable).where(eq(claimEvidenceTable.claimId, id)).catch(() => undefined);
  await db.delete(claimsTable).where(eq(claimsTable.id, id)).catch(() => undefined);
}

async function cleanupGroup(id: number) {
  const children = await db.select({ id: claimsTable.id }).from(claimsTable).where(eq(claimsTable.invoiceGroupId, id));
  for (const c of children) await cleanupClaim(c.id);
  await db.delete(stateEventsTable).where(eq(stateEventsTable.invoiceGroupId, id)).catch(() => undefined);
  await db.delete(portalSubmissionsTable).where(eq(portalSubmissionsTable.invoiceGroupId, id)).catch(() => undefined);
  await db.delete(auditLogsTable).where(eq(auditLogsTable.invoiceGroupId, id)).catch(() => undefined);
  await db.delete(claimEvidenceTable).where(eq(claimEvidenceTable.invoiceGroupId, id)).catch(() => undefined);
  await db.delete(invoiceGroupsTable).where(eq(invoiceGroupsTable.id, id)).catch(() => undefined);
}

async function cleanupErrorType(id: number) {
  await db.delete(errorTypesTable).where(eq(errorTypesTable.id, id)).catch(() => undefined);
}

// --- /classify ----------------------------------------------------------

test("POST /claims/:id/classify writes errorTypeId+name and emits leg.classified", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/classify`, {
      method: "POST",
      body: { errorTypeId: String(errType.id) },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.errorTypeId, String(errType.id));
    assert.equal(res.json.errorTypeName, errType.name);

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    assert.ok(audits.find((a) => a.action === "leg_classified"), "expected leg_classified audit row");

    const events = await db.select().from(stateEventsTable).where(eq(stateEventsTable.claimId, claim.id));
    assert.ok(events.find((e) => e.eventKey === "leg.classified"), "expected leg.classified state_events row");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/classify on already-classified leg returns 409 with expected/actual states", async () => {
  const errType = await createSeedErrorType();
  // Pre-classified: errorTypeId is set, so sub-status should be `investigating`.
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/classify`, {
      method: "POST",
      body: { errorTypeId: String(errType.id) },
    });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "needs_classification");
    assert.equal(res.json.actualState, "investigating");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /sop-advance -------------------------------------------------------

test("POST /claims/:id/sop-advance walks one step and reaches a ready terminal", async () => {
  // Tiny tree: root has one option that leads straight to a portal_dispute
  // terminal so the leg lands in `ready`.
  const tree = {
    rootId: "root",
    nodes: [
      {
        id: "root",
        question: "Is this a dispute?",
        options: [
          { label: "yes", outcomeType: "portal_dispute", outcomeLabel: "Dispute via portal" },
          { label: "no", outcomeType: "internal", outcomeLabel: "Cannot dispute" },
        ],
      },
    ],
  };
  const errType = await createSeedErrorType(tree);
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/sop-advance`, {
      method: "POST",
      body: { nodeId: "root", answer: "yes" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.sopOutcome, "portal_dispute");
    assert.ok(res.json.readyAt, "ready terminal must stamp readyAt");
    // Per contract, terminal sop-advance also persists sopNodeId to
    // the terminal node identifier (here, "root" — the question that
    // reached the terminal).
    assert.equal(res.json.sopNodeId, "root", "terminal sop-advance must persist sopNodeId");

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    // Per contract, every sop-advance (terminal or mid-walk) writes
    // a single `leg_sop_advanced` audit row; the `isTerminal` field in
    // the metadata distinguishes the two.
    const terminalAudit = audits.find((a) => a.action === "leg_sop_advanced" && (a.metadata as any)?.isTerminal === true);
    assert.ok(terminalAudit, "expected leg_sop_advanced audit row with isTerminal=true");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/sop-advance terminal `internal` lands at sopOutcome=cannot_dispute and stamps droppedAt", async () => {
  const tree = {
    rootId: "root",
    nodes: [{
      id: "root",
      question: "?",
      options: [{ label: "no", outcomeType: "internal", outcomeLabel: "Internal" }],
    }],
  };
  const errType = await createSeedErrorType(tree);
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/sop-advance`, {
      method: "POST", body: { nodeId: "root", answer: "no" },
    });
    assert.equal(res.status, 200);
    assert.equal(res.json.sopOutcome, "cannot_dispute");
    assert.equal(res.json.dropReason, "cannot_dispute");
    assert.ok(res.json.droppedAt);
    // cannot_dispute terminal triggers MAS-cancel derivation.
    assert.equal(res.json.masActionRequired, "cancel",
      "cannot_dispute terminal must derive mas_action_required=cancel");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/sop-advance with an unknown answer returns 400 and does not mutate the leg", async () => {
  const tree = {
    rootId: "root",
    nodes: [{ id: "root", question: "?", options: [{ label: "yes", outcomeType: "portal_dispute" }] }],
  };
  const errType = await createSeedErrorType(tree);
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/sop-advance`, {
      method: "POST", body: { nodeId: "root", answer: "maybe" },
    });
    assert.equal(res.status, 400);
    assert.ok(Array.isArray(res.json.validOptions));

    const [post] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(post.sopOutcome, null, "leg must remain untouched on validation failure");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /hold + /clear-hold + /clear-hold (POST alias) --------------------

test("POST /claims/:id/hold places hold from `investigating` and DELETE clears it", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const placed = await fetchJson(`/api/claims/${claim.id}/hold`, {
      method: "POST", body: { reason: "awaiting_member_response", note: "called twice" },
    });
    assert.equal(placed.status, 200, `expected 200, got ${placed.status} (${JSON.stringify(placed.json)})`);
    assert.equal(placed.json.holdReason, "awaiting_member_response");
    assert.ok(placed.json.holdPlacedAt);

    const cleared = await fetchJson(`/api/claims/${claim.id}/hold`, { method: "DELETE" });
    assert.equal(cleared.status, 200);
    assert.equal(cleared.json.holdReason, null);
    assert.equal(cleared.json.holdPlacedAt, null);
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/hold with bogus reason returns 400 and does not mutate", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/hold`, {
      method: "POST", body: { reason: "not_a_real_reason" },
    });
    assert.equal(res.status, 400);
    const [post] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(post.holdReason, null);
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/hold from `needs_classification` returns 409", async () => {
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/hold`, {
      method: "POST", body: { reason: "awaiting_member_response" },
    });
    assert.equal(res.status, 409);
    assert.equal(res.json.actualState, "needs_classification");
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("POST /claims/:id/clear-hold mirrors DELETE", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    holdReason: "awaiting_member_response",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/clear-hold`, { method: "POST" });
    assert.equal(res.status, 200);
    assert.equal(res.json.holdReason, null);
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /reclassify --------------------------------------------------------

test("POST /claims/:id/reclassify wipes errorType + SOP + hold and bounces back to needs_classification", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "portal_dispute",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/reclassify`, { method: "POST" });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.errorTypeId, null);
    assert.equal(res.json.errorTypeName, null);
    assert.equal(res.json.sopOutcome, null);
    assert.equal(res.json.holdReason, null);
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/reclassify is refused once a portal submission is in flight", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup();
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "portal_dispute",
    invoiceGroupId: group.id,
  });
  // Insert a submitted portal submission to lock the leg.
  await db.insert(portalSubmissionsTable).values({
    invoiceGroupId: group.id,
    status: "submitted",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/reclassify`, { method: "POST" });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "no_submission");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /verdict -----------------------------------------------------------

test("POST /claims/:id/verdict (operator_confirmed Denied) writes claim_verdict and derives mas_action_required=cancel", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "dispute",
    invoiceGroupId: group.id,
    status: "Needs Review",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/verdict`, {
      method: "POST", body: { source: "operator_confirmed", outcome: "Denied" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.outcome, "Denied");

    const verdicts = await db.select().from(claimVerdictTable).where(eq(claimVerdictTable.claimId, claim.id));
    assert.equal(verdicts.length, 1);

    const [post] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(post.outcome, "Denied", "operator-confirmed verdict must refresh denormalized claims.outcome");
    assert.equal(post.masActionRequired, "cancel", "Denied must derive mas_action_required=cancel");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/verdict refuses operator confirmation on a non-submitted leg", async () => {
  // Leg is included in dispute but its sopOutcome is `cannot_dispute`
  // (was never submitted) — the operator-confirmed verdict path must
  // refuse it. Task #301 also stamps a machine-readable `reason` on the
  // 409 body so the UI can route the operator into the reconcile flow.
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "cannot_dispute",
    invoiceGroupId: group.id,
    status: "Needs Review",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/verdict`, {
      method: "POST", body: { source: "operator_confirmed", outcome: "Approved" },
    });
    assert.equal(res.status, 409);
    assert.equal(
      res.json.reason,
      "leg_not_in_submission",
      "409 body must carry the machine reason so the UI can route to the reconcile path",
    );
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- Task #301: legacy reconcile path -----------------------------------

test("POST /claims/:id/verdict { reconcile: true } records a verdict on a NULL-sopOutcome legacy leg", async () => {
  // The two stuck legs in the field had sop_outcome=NULL because they
  // pre-date the invoice-group flow. The reconcile flag should bypass
  // ONLY the sop_outcome gate and otherwise behave like a normal
  // operator-confirmed verdict (verdict row inserted, denormalized
  // outcome refreshed, audit row tagged with the reason).
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: null,
    invoiceGroupId: group.id,
    status: "Needs Review",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/verdict`, {
      method: "POST",
      body: {
        source: "operator_confirmed",
        outcome: "Approved",
        note: "Payor email on Apr 30 confirmed approval.",
        reconcile: true,
      },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.outcome, "Approved");

    const verdicts = await db.select().from(claimVerdictTable).where(eq(claimVerdictTable.claimId, claim.id));
    assert.equal(verdicts.length, 1);
    assert.equal(verdicts[0].source, "operator_confirmed");
    assert.equal(verdicts[0].note, "Payor email on Apr 30 confirmed approval.");

    const [post] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(post.outcome, "Approved", "denormalized claims.outcome must update via the reconcile path");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/verdict { reconcile: true } still 409s when the leg is excluded from the dispute", async () => {
  // The reconcile flag bypasses ONLY the sop_outcome gate. Other
  // source-state gates (group phase, included_in_dispute) still apply.
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: null,
    invoiceGroupId: group.id,
    status: "Needs Review",
    includedInDispute: false,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/verdict`, {
      method: "POST",
      body: {
        source: "operator_confirmed",
        outcome: "Denied",
        note: "Trying to reconcile an excluded leg.",
        reconcile: true,
      },
    });
    assert.equal(res.status, 409, `expected 409, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.expectedState, "included_in_dispute");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/verdict { reconcile: true } refuses without an operator note", async () => {
  // The reconcile path requires a human-supplied note so the audit row
  // carries an explanation. Without it (or with whitespace only), the
  // request must 400.
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: null,
    invoiceGroupId: group.id,
    status: "Needs Review",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/verdict`, {
      method: "POST",
      body: {
        source: "operator_confirmed",
        outcome: "Approved",
        note: "   ",
        reconcile: true,
      },
    });
    assert.equal(res.status, 400, `expected 400, got ${res.status} (${JSON.stringify(res.json)})`);
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- Task #344: DELETE /claims/:id/verdict/draft ----------------------

test("DELETE /claims/:id/verdict/draft hard-deletes operator_draft rows and writes a clear audit + state event", async () => {
  // Happy path: operator picks Approved (draft saved), then clicks the
  // lit pill to clear it. The endpoint MUST hard-delete the draft row,
  // emit `leg.verdict_draft_cleared` + `leg_verdict_draft_cleared`, and
  // return `clearedCount: 1`.
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "dispute",
    invoiceGroupId: group.id,
    status: "Needs Review",
  });
  try {
    const draftRes = await fetchJson(`/api/claims/${claim.id}/verdict`, {
      method: "POST",
      body: { source: "operator_draft", outcome: "Approved" },
    });
    assert.equal(draftRes.status, 200);

    const clearRes = await fetchJson(
      `/api/claims/${claim.id}/verdict/draft`,
      { method: "DELETE" },
    );
    assert.equal(
      clearRes.status,
      200,
      `expected 200, got ${clearRes.status} (${JSON.stringify(clearRes.json)})`,
    );
    assert.equal(clearRes.json.clearedCount, 1);

    // Draft row is gone — drafts are explicitly transient state, so
    // hard-delete is the contract.
    const remaining = await db
      .select()
      .from(claimVerdictTable)
      .where(eq(claimVerdictTable.claimId, claim.id));
    assert.equal(remaining.length, 0);

    // Audit + state-event vocabulary pinned so observability stays
    // consistent.
    const audits = await db
      .select()
      .from(auditLogsTable)
      .where(and(
        eq(auditLogsTable.claimId, claim.id),
        eq(auditLogsTable.action, "leg_verdict_draft_cleared"),
      ));
    assert.equal(audits.length, 1, "audit row must be written on a non-empty clear");
    const events = await db
      .select()
      .from(stateEventsTable)
      .where(and(
        eq(stateEventsTable.claimId, claim.id),
        eq(stateEventsTable.eventKey, "leg.verdict_draft_cleared"),
      ));
    assert.equal(events.length, 1, "state event must be emitted on a non-empty clear");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("DELETE /claims/:id/verdict/draft is idempotent — returns clearedCount=0 with no audit row", async () => {
  // Calling clear on a leg with no draft (e.g. operator double-clicks
  // or the page racing optimistic state) MUST NOT 404 or 409. It
  // returns `clearedCount: 0` and skips the audit + state-event write
  // so the audit log stays clean.
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "dispute",
    invoiceGroupId: group.id,
    status: "Needs Review",
  });
  try {
    const res = await fetchJson(
      `/api/claims/${claim.id}/verdict/draft`,
      { method: "DELETE" },
    );
    assert.equal(res.status, 200);
    assert.equal(res.json.clearedCount, 0);

    const audits = await db
      .select()
      .from(auditLogsTable)
      .where(and(
        eq(auditLogsTable.claimId, claim.id),
        eq(auditLogsTable.action, "leg_verdict_draft_cleared"),
      ));
    assert.equal(audits.length, 0, "no audit row should be written on a no-op clear");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("DELETE /claims/:id/verdict/draft does NOT touch operator_confirmed or ai_suggested rows", async () => {
  // Append-only-ness is preserved for terminal rows. We seed an
  // operator_confirmed verdict, then a draft on top, then call clear.
  // Only the draft row should be deleted.
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "dispute",
    invoiceGroupId: group.id,
    status: "Needs Review",
  });
  try {
    // Insert a terminal operator_confirmed row directly so we don't
    // re-trigger the MAS / attestation side effects of the POST path.
    // (The endpoint under test is supposed to leave this row alone
    // regardless of how it got there.)
    await db.insert(claimVerdictTable).values({
      claimId: claim.id,
      source: "operator_confirmed",
      outcome: "Approved",
    });
    // And a draft on top.
    await db.insert(claimVerdictTable).values({
      claimId: claim.id,
      source: "operator_draft",
      outcome: "Denied",
    });

    const res = await fetchJson(
      `/api/claims/${claim.id}/verdict/draft`,
      { method: "DELETE" },
    );
    assert.equal(res.status, 200);
    assert.equal(res.json.clearedCount, 1);

    const remaining = await db
      .select()
      .from(claimVerdictTable)
      .where(eq(claimVerdictTable.claimId, claim.id));
    assert.equal(remaining.length, 1);
    assert.equal(remaining[0].source, "operator_confirmed");
    assert.equal(remaining[0].outcome, "Approved");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("DELETE /claims/:id/verdict/draft 409s when the parent group is past response-pending", async () => {
  // Mirror of POST /verdict's macro-phase gate. Once Step 4 has been
  // committed and the group has moved on, there's no longer a draft
  // to clear and we refuse the call so a stale tab can't reach back
  // and mutate a sealed group.
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Resolved" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "dispute",
    invoiceGroupId: group.id,
    status: "Resolved",
  });
  try {
    const res = await fetchJson(
      `/api/claims/${claim.id}/verdict/draft`,
      { method: "DELETE" },
    );
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "response-pending");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /mas-action/complete ----------------------------------------------

test("POST /claims/:id/mas-action/complete stamps completion when mas_action_required=cancel", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  // Force the precondition state directly.
  await db.update(claimsTable).set({ masActionRequired: "cancel" }).where(eq(claimsTable.id, claim.id));
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/mas-action/complete`, {
      method: "POST", body: { masReference: "MAS-12345" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.ok(res.json.masActionCompletedAt);
    assert.equal(res.json.masActionCompletedBy, TEST_USER.email);
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/mas-action/complete on a leg without an open cancel returns 409", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/mas-action/complete`, { method: "POST", body: {} });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "mas_action_required=cancel");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /invoice-groups/:id/group-context ---------------------------------

test("POST /invoice-groups/:id/group-context records context in pre-submit", async () => {
  const group = await createSeedGroup({ status: "Needs Evidence" });
  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/group-context`, {
      method: "POST", body: { context: "Driver said the unit was rejected at the gate." },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.groupContext, "Driver said the unit was rejected at the gate.");
  } finally {
    await cleanupGroup(group.id);
  }
});

test("POST /invoice-groups/:id/group-context outside pre-submit returns 409", async () => {
  const group = await createSeedGroup({ status: "Needs Review" });
  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/group-context`, {
      method: "POST", body: { context: "anything" },
    });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "pre-submit");
  } finally {
    await cleanupGroup(group.id);
  }
});

// --- /invoice-groups/:id/understanding-readback ------------------------

test("POST /invoice-groups/:id/understanding-readback requires every disputed leg to be resolved", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Evidence" });
  // Disputed but unresolved leg (sopOutcome=null → investigating).
  await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
  });
  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/understanding-readback`, {
      method: "POST", body: { readback: "We're disputing the gate-rejection unit." },
    });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "all-legs-resolved");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /invoice-groups/:id/understanding-readback succeeds once disputed legs are resolved", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Evidence" });
  // Resolved disputed leg (sopOutcome=portal_dispute → ready).
  await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "portal_dispute",
  });
  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/understanding-readback`, {
      method: "POST", body: { readback: "We're disputing the gate-rejection unit." },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.ok(res.json.understandingReadbackAt);
    assert.equal(res.json.understandingReadbackBy, TEST_USER.email);
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /invoice-groups/:id/preview-generated -----------------------------

test("POST /invoice-groups/:id/preview-generated no longer requires readback — readback is optional", async () => {
  // Readback was previously required to unlock preview generation. It is
  // now OPTIONAL — the preview can be generated as soon as every disputed
  // leg is resolved, regardless of whether the operator wrote notes.
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Evidence" });
  await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "portal_dispute",
  });
  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/preview-generated`, { method: "POST" });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.ok(res.json.previewGeneratedAt);
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /invoice-groups/:id/preview-generated succeeds after readback + resolution", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Evidence" });
  await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "portal_dispute",
  });
  try {
    const r1 = await fetchJson(`/api/invoice-groups/${group.id}/understanding-readback`, {
      method: "POST", body: { readback: "ok" },
    });
    assert.equal(r1.status, 200);
    const res = await fetchJson(`/api/invoice-groups/${group.id}/preview-generated`, { method: "POST" });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.ok(res.json.previewGeneratedAt);
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /invoice-groups/:id/reattest/complete (the trigger gate) ----------

test("POST /invoice-groups/:id/reattest/complete graduates Approved verdict legs to attestation pending", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  // Mark the group as needing reattest (would normally be set by the
  // refreshGroupDerivedFields helper after a payor response landed).
  // Wave C: macro-phase reader pulls `phase` directly. Promote the
  // group to `awaiting_reattestation` alongside the legacy reattest
  // flag so getGroupMacroPhase returns "mas-action-required".
  await db.update(invoiceGroupsTable).set({ reattestRequired: true, phase: "awaiting_reattestation" })
    .where(eq(invoiceGroupsTable.id, group.id));
  // Disputed, submitted leg with an Approved operator verdict.
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "dispute",
    status: "Needs Review",
    outcome: "Approved",
  });
  await db.insert(claimVerdictTable).values({
    claimId: claim.id,
    source: "operator_confirmed",
    outcome: "Approved",
    createdBy: TEST_USER.email,
  });
  try {
    // Sanity: pre-call, attestation_state should still be not_required.
    const [pre] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(pre.attestationState, "not_required",
      "leg must start at not_required before the gate engages");

    const res = await fetchJson(`/api/invoice-groups/${group.id}/reattest/complete`, {
      method: "POST", body: { masReference: "MAS-99" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.ok(res.json.reattestCompletedAt);

    const [post] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(post.attestationState, "pending",
      "after reattest/complete, Approved verdict legs must graduate to attestation=pending");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /invoice-groups/:id/reattest/complete is refused while MAS cancel actions are still open", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  // Wave C: phase column drives macro-phase derivation; mark the
  // group as awaiting_reattestation so the route reaches the
  // cancel-completeness gate (the assertion under test).
  await db.update(invoiceGroupsTable).set({ reattestRequired: true, phase: "awaiting_reattestation" })
    .where(eq(invoiceGroupsTable.id, group.id));
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "dispute",
    status: "Needs Review",
  });
  await db.update(claimsTable).set({ masActionRequired: "cancel" })
    .where(eq(claimsTable.id, claim.id));
  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/reattest/complete`, {
      method: "POST", body: {},
    });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "all-cancels-complete");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- MAS derivation preservation ---------------------------------------

import { applyMasDerivationsForLeg, deriveMasActionRequired } from "../lib/mas-derivations";

test("deriveMasActionRequired returns null for Approved/Partial (preserves caller's existing value)", () => {
  assert.equal(deriveMasActionRequired({ latestOperatorVerdictOutcome: "Approved" }), null);
  assert.equal(deriveMasActionRequired({ latestOperatorVerdictOutcome: "Partial" }), null);
});

test("deriveMasActionRequired still maps Denied → cancel and SOP cannot_dispute → cancel", () => {
  assert.equal(deriveMasActionRequired({ latestOperatorVerdictOutcome: "Denied" }), "cancel");
  assert.equal(deriveMasActionRequired({ sopOutcome: "cannot_dispute" }), "cancel");
  assert.equal(deriveMasActionRequired({ sopOutcome: "non_issue" }), "none");
});

test("applyMasDerivationsForLeg preserves an existing 'cancel' when an Approved verdict lands later", async () => {
  const claim = await createSeedClaim({});
  try {
    // Seed a 'cancel' requirement on the leg (simulating a prior
    // SOP terminal cannot_dispute that was later reclassified).
    await db.update(claimsTable).set({ masActionRequired: "cancel" }).where(eq(claimsTable.id, claim.id));
    const result = await applyMasDerivationsForLeg(claim.id, "Approved");
    assert.ok(result, "expected the leg row back");
    assert.equal(result!.masActionRequired, "cancel", "Approved must NOT clear an existing cancel");
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("applyMasDerivationsForLeg sets 'none' on Approved when masActionRequired was null", async () => {
  const claim = await createSeedClaim({});
  try {
    // Default seeded leg has masActionRequired = null.
    const result = await applyMasDerivationsForLeg(claim.id, "Approved");
    assert.ok(result, "expected the leg row back");
    assert.equal(result!.masActionRequired, "none", "Approved on null should render the checklist row");
  } finally {
    await cleanupClaim(claim.id);
  }
});

// --- getAiCalibration helper -------------------------------------------

import { getAiCalibration } from "../lib/ai-calibration";

test("getAiCalibration returns the contracted shape with zeroed fields when no verdicts exist", async () => {
  const stats = await getAiCalibration({ errorTypeId: "no-such-error-type", windowDays: 30 });
  assert.equal(stats.errorTypeId, "no-such-error-type");
  assert.equal(stats.totalConfirmations, 0);
  assert.equal(stats.agreementCount, 0);
  assert.deepEqual(stats.perOutcomeAgreement, { Approved: 0, Denied: 0, Partial: 0 });
  assert.equal(stats.windowDays, 30);
});

test("getAiCalibration counts agreement when AI suggestion matches operator confirmation", async () => {
  const errType = await createSeedErrorType();
  const errorTypeId = String(errType.id);
  const claim = await createSeedClaim({ errorTypeId });
  try {
    // AI suggested Approved → operator confirmed Approved (match).
    await db.insert(claimVerdictTable).values({
      claimId: claim.id, source: "ai_suggested", outcome: "Approved",
      createdBy: TEST_USER.email,
    });
    await db.insert(claimVerdictTable).values({
      claimId: claim.id, source: "operator_confirmed", outcome: "Approved",
      createdBy: TEST_USER.email,
    });

    const stats = await getAiCalibration({ errorTypeId, windowDays: 90 });
    assert.equal(stats.errorTypeId, errorTypeId);
    assert.equal(stats.totalConfirmations, 1);
    assert.equal(stats.agreementCount, 1);
    assert.equal(stats.perOutcomeAgreement.Approved, 1);
    assert.equal(stats.perOutcomeAgreement.Denied, 0);
    assert.equal(stats.perOutcomeAgreement.Partial, 0);
    assert.equal(stats.windowDays, 90);
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("getAiCalibration does not count AI/operator mismatches as agreement", async () => {
  const errType = await createSeedErrorType();
  const errorTypeId = String(errType.id);
  const claim = await createSeedClaim({ errorTypeId });
  try {
    await db.insert(claimVerdictTable).values({
      claimId: claim.id, source: "ai_suggested", outcome: "Approved",
      createdBy: TEST_USER.email,
    });
    await db.insert(claimVerdictTable).values({
      claimId: claim.id, source: "operator_confirmed", outcome: "Denied",
      createdBy: TEST_USER.email,
    });

    const stats = await getAiCalibration({ errorTypeId });
    assert.equal(stats.totalConfirmations, 1);
    assert.equal(stats.agreementCount, 0);
    assert.deepEqual(stats.perOutcomeAgreement, { Approved: 0, Denied: 0, Partial: 0 });
    // Default window of 90 days when not provided.
    assert.equal(stats.windowDays, 90);
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /invoice-groups/:id/reattest/complete on a group that doesn't need reattest returns 409", async () => {
  // Force a pre-submit fingerprint so neither the phase gate nor the
  // outlook gate accepts the call — see commentary in the assertion
  // below for why a bare seed group (status=Needs Review →
  // phase=response_received → macro=response-pending) is now an
  // ACCEPTED state and would no longer 409.
  const group = await createSeedGroup({ status: "Needs Evidence" });
  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/reattest/complete`, {
      method: "POST", body: {},
    });
    assert.equal(res.status, 409);
    // The endpoint enforces the queue-gate's three-condition accept-set
    // (mas-action-required OR response-pending OR reattest_only outlook)
    // rather than the raw flag — see invoice-groups.ts:/reattest/complete.
    // A bare seed group has status="Needs Review" → macro=response-pending,
    // which would now be ACCEPTED by the phase gate; force the group into
    // a pre-submit phase with no legs so neither phase nor outlook
    // qualifies and the 409 path remains exercised.
    assert.equal(
      res.json.expectedState,
      "macroPhase in (mas-action-required, response-pending) OR outlook=reattest_only",
    );
  } finally {
    await cleanupGroup(group.id);
  }
});

// --- /exclude + /include -----------------------------------------------

test("POST /claims/:id/exclude from needs_classification writes includedInDispute=false and emits leg.excluded", async () => {
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "clean_leg" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, false);

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    assert.ok(audits.find((a) => a.action === "leg_excluded"), "expected leg_excluded audit row");

    const events = await db.select().from(stateEventsTable).where(eq(stateEventsTable.claimId, claim.id));
    assert.ok(events.find((e) => e.eventKey === "leg.excluded"), "expected leg.excluded state_events row");
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("POST /claims/:id/exclude from `investigating` clears classification fields and excludes the leg", async () => {
  // 2026-05-14 — operators legitimately want to pull a classified-but-
  // unwalked (or partially walked) leg out of the dispute when they
  // realise mid-walk that it's a clean ride. The exclude route now
  // accepts `investigating` as a source state, mirrors /reclassify's
  // field-clearing set inside the same transaction, then runs the
  // shared excludeLegCore writer. The audit row's `previousSubStatus`
  // metadata records the real prior state.
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "clean_leg" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, false);
    assert.equal(res.json.errorTypeId, null, "errorTypeId must be cleared");
    assert.equal(res.json.errorTypeName, null, "errorTypeName must be cleared");
    assert.equal(res.json.sopOutcome, null, "sopOutcome must be cleared");

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    const excluded = audits.find((a) => a.action === "leg_excluded");
    assert.ok(excluded, "expected leg_excluded audit row");
    type Meta = { previousSubStatus?: string } | null;
    const meta = excluded!.metadata as Meta;
    assert.equal(meta?.previousSubStatus, "investigating",
      "audit metadata must record the real prior sub-status, not the default `needs_classification`");

    const events = await db.select().from(stateEventsTable).where(eq(stateEventsTable.claimId, claim.id));
    assert.ok(events.find((e) => e.eventKey === "leg.excluded"), "expected leg.excluded state_events row");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/exclude against a leg with sub-status `excluded` still returns 409", async () => {
  // The expanded source-state allow-list is {needs_classification,
  // investigating}. Already-excluded legs (and every other state) must
  // still be rejected so the route can't double-exclude or pull a leg
  // out of a terminal classified state.
  const claim = await createSeedClaim({
    errorTypeId: null,
    includedInDispute: false,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "clean_leg" },
    });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "needs_classification|investigating");
    assert.equal(res.json.actualState, "excluded");
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("POST /claims/:id/exclude with reason=other and missing note returns 400", async () => {
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "other" },
    });
    assert.equal(res.status, 400);
    assert.ok(res.json.error.includes("note required"), `expected note-required error, got: ${res.json.error}`);
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("POST /claims/:id/include re-includes an excluded leg in pre-submit and emits leg.included", async () => {
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
    includedInDispute: false,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: { note: "re-including after review" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, true);

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    assert.ok(audits.find((a) => a.action === "leg_included"), "expected leg_included audit row");

    const events = await db.select().from(stateEventsTable).where(eq(stateEventsTable.claimId, claim.id));
    assert.ok(events.find((e) => e.eventKey === "leg.included"), "expected leg.included state_events row");
  } finally {
    await cleanupGroup(group.id);
  }
});

test("POST /claims/:id/include against an excluded leg whose group is in response-pending returns 409 group-phase variant", async () => {
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
    includedInDispute: false,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: {},
    });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "pre-submit");
    assert.equal(res.json.actualState, "response-pending");
  } finally {
    await cleanupGroup(group.id);
  }
});

// --- Importer excludedCount + includedInDispute default ----------------

test("Importer sets includedInDispute=false for rows without errorTypeId and reports excludedCount", async () => {
  const base = Date.now() % 1_000_000_000;
  const withError = String(base * 10 + 1);
  const withoutError = String(base * 10 + 2);
  try {
    const res = await fetchJson("/api/import", {
      method: "POST",
      body: {
        rows: [
          { confNumber: withError, errorTypeId: "99", errorTypeName: "Test Error", errorDetails: "something" },
          { confNumber: withoutError, errorDetails: "clean" },
        ],
      },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.created, 2);
    assert.equal(res.json.excludedCount, 1, "one row has no errorTypeId → excluded");

    const [withErrRow] = await db.select().from(claimsTable).where(eq(claimsTable.confNumber, withError));
    assert.equal(withErrRow.includedInDispute, true, "row with errorTypeId must be included");

    const [noErrRow] = await db.select().from(claimsTable).where(eq(claimsTable.confNumber, withoutError));
    assert.equal(noErrRow.includedInDispute, false, "row without errorTypeId must be excluded");
  } finally {
    const rows = await db.select({ id: claimsTable.id }).from(claimsTable)
      .where(eq(claimsTable.confNumber, withError));
    for (const r of rows) await cleanupClaim(r.id);
    const rows2 = await db.select({ id: claimsTable.id }).from(claimsTable)
      .where(eq(claimsTable.confNumber, withoutError));
    for (const r of rows2) await cleanupClaim(r.id);
  }
});

// --- Backfill migration 0012 -------------------------------------------

test("Backfill migration 0012 flips matching rows to false and is idempotent", async () => {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const sqlPath = path.resolve(here, "../../../../lib/db/drizzle/0012_backfill_excluded_legs.sql");
  const sql = fs.readFileSync(sqlPath, "utf8");

  const seedNoErr = `T209-BF-${Date.now()}-${Math.floor(Math.random() * 1e6)}`;
  const seedWithErr = `T209-BF-${Date.now()}-${Math.floor(Math.random() * 1e6 + 1e6)}`;
  const seedAlreadyFalse = `T209-BF-${Date.now()}-${Math.floor(Math.random() * 1e6 + 2e6)}`;

  const [matching] = await db.insert(claimsTable).values({
    confNumber: seedNoErr,
    status: "New",
    outcome: "Pending",
    errorTypeId: null,
    includedInDispute: true,
    claimAmount: "100.00",
  }).returning();

  const [withErr] = await db.insert(claimsTable).values({
    confNumber: seedWithErr,
    status: "New",
    outcome: "Pending",
    errorTypeId: "42",
    errorTypeName: "Some Error",
    includedInDispute: true,
    claimAmount: "100.00",
  }).returning();

  const [alreadyFalse] = await db.insert(claimsTable).values({
    confNumber: seedAlreadyFalse,
    status: "New",
    outcome: "Pending",
    errorTypeId: null,
    includedInDispute: false,
    claimAmount: "100.00",
  }).returning();

  try {
    await pool.query(sql);

    const [m1] = await db.select().from(claimsTable).where(eq(claimsTable.id, matching.id));
    assert.equal(m1.includedInDispute, false, "matching New + no-error row must flip to false");

    const [w1] = await db.select().from(claimsTable).where(eq(claimsTable.id, withErr.id));
    assert.equal(w1.includedInDispute, true, "row with errorTypeId must NOT flip");

    const [f1] = await db.select().from(claimsTable).where(eq(claimsTable.id, alreadyFalse.id));
    assert.equal(f1.includedInDispute, false, "already-false row must remain false");

    await pool.query(sql);

    const [m2] = await db.select().from(claimsTable).where(eq(claimsTable.id, matching.id));
    assert.equal(m2.includedInDispute, false, "second run is idempotent — still false");

    const [w2] = await db.select().from(claimsTable).where(eq(claimsTable.id, withErr.id));
    assert.equal(w2.includedInDispute, true, "second run does not touch error-type rows");
  } finally {
    await cleanupClaim(matching.id);
    await cleanupClaim(withErr.id);
    await cleanupClaim(alreadyFalse.id);
  }
});

// --- /clear-sop-hold (Task #212) -----------------------------------------

test("POST /claims/:id/clear-sop-hold clears a SOP hold and returns to investigating", async () => {
  const tree = {
    rootId: "root",
    nodes: [{
      id: "root",
      question: "Should we hold?",
      options: [
        { label: "yes", outcomeType: "hold", outcomeLabel: "Place on hold" },
        { label: "no", outcomeType: "portal_dispute", outcomeLabel: "Dispute" },
      ],
    }],
  };
  const errType = await createSeedErrorType(tree);
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const advRes = await fetchJson(`/api/claims/${claim.id}/sop-advance`, {
      method: "POST", body: { nodeId: "root", answer: "yes" },
    });
    assert.equal(advRes.status, 200);
    assert.equal(advRes.json.sopOutcome, "hold");
    assert.equal(advRes.json.holdReason, null);
    assert.ok(advRes.json.sopNodeId, "sopNodeId must be set on hold terminal");

    const deleteHold = await fetchJson(`/api/claims/${claim.id}/hold`, { method: "DELETE" });
    assert.equal(deleteHold.status, 409, "DELETE /hold must 409 on SOP-held legs (no holdReason)");

    const clearHold = await fetchJson(`/api/claims/${claim.id}/clear-hold`, { method: "POST" });
    assert.equal(clearHold.status, 409, "POST /clear-hold must 409 on SOP-held legs (no holdReason)");

    const clearSop = await fetchJson(`/api/claims/${claim.id}/clear-sop-hold`, { method: "POST" });
    assert.equal(clearSop.status, 200, `expected 200, got ${clearSop.status} (${JSON.stringify(clearSop.json)})`);
    assert.equal(clearSop.json.sopOutcome, null, "sopOutcome must be cleared");
    assert.equal(clearSop.json.sopNodeId, "root", "sopNodeId must be preserved");
    assert.ok(Array.isArray(clearSop.json.sopAnswers) && clearSop.json.sopAnswers.length > 0, "sopAnswers must be preserved");
    assert.equal(clearSop.json.errorTypeId, String(errType.id), "errorTypeId must be preserved");

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    assert.ok(audits.find((a) => a.action === "leg_sop_hold_cleared"), "expected leg_sop_hold_cleared audit row");

    const events = await db.select().from(stateEventsTable).where(eq(stateEventsTable.claimId, claim.id));
    assert.ok(events.find((e) => e.eventKey === "leg.sop_hold_cleared"), "expected leg.sop_hold_cleared state_events row");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/clear-sop-hold returns 409 on operator-held legs", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    holdReason: "awaiting_member_response",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/clear-sop-hold`, { method: "POST" });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "sop_outcome=hold");
    assert.equal(res.json.actualState, "null", "operator-held legs have sop_outcome=null");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/clear-sop-hold returns 409 on investigating legs (no hold at all)", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/clear-sop-hold`, { method: "POST" });
    assert.equal(res.status, 409);
    assert.equal(res.json.actualState, "null");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("Clear SOP hold then re-walk to the same terminal — same behavior as first walk", async () => {
  const tree = {
    rootId: "root",
    nodes: [{
      id: "root",
      question: "Should we hold?",
      options: [
        { label: "yes", outcomeType: "hold", outcomeLabel: "Place on hold" },
        { label: "no", outcomeType: "portal_dispute", outcomeLabel: "Dispute" },
      ],
    }],
  };
  const errType = await createSeedErrorType(tree);
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const adv1 = await fetchJson(`/api/claims/${claim.id}/sop-advance`, {
      method: "POST", body: { nodeId: "root", answer: "yes" },
    });
    assert.equal(adv1.status, 200);
    assert.equal(adv1.json.sopOutcome, "hold");
    const firstAnswersCount = adv1.json.sopAnswers.length;

    const clear = await fetchJson(`/api/claims/${claim.id}/clear-sop-hold`, { method: "POST" });
    assert.equal(clear.status, 200);
    assert.equal(clear.json.sopOutcome, null);
    assert.equal(clear.json.sopAnswers.length, firstAnswersCount, "answers preserved after clear");

    const adv2 = await fetchJson(`/api/claims/${claim.id}/sop-advance`, {
      method: "POST", body: { nodeId: "root", answer: "yes" },
    });
    assert.equal(adv2.status, 200);
    assert.equal(adv2.json.sopOutcome, "hold");
    assert.equal(adv2.json.sopAnswers.length, firstAnswersCount + 1, "answers appended on re-walk");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

test("Operator-hold regression: POST /hold + DELETE /hold path is unchanged by clear-sop-hold", async () => {
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({ errorTypeId: String(errType.id), errorTypeName: errType.name });
  try {
    const placed = await fetchJson(`/api/claims/${claim.id}/hold`, {
      method: "POST", body: { reason: "evidence_pending", note: "waiting on docs" },
    });
    assert.equal(placed.status, 200);
    assert.equal(placed.json.holdReason, "evidence_pending");
    assert.ok(placed.json.holdPlacedAt);

    const sopHoldRes = await fetchJson(`/api/claims/${claim.id}/clear-sop-hold`, { method: "POST" });
    assert.equal(sopHoldRes.status, 409, "clear-sop-hold must refuse operator-held legs");

    const cleared = await fetchJson(`/api/claims/${claim.id}/hold`, { method: "DELETE" });
    assert.equal(cleared.status, 200);
    assert.equal(cleared.json.holdReason, null);
    assert.equal(cleared.json.holdPlacedAt, null);

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    assert.ok(audits.find((a) => a.action === "leg_hold_placed"), "expected leg_hold_placed audit row");
    assert.ok(audits.find((a) => a.action === "leg_hold_cleared"), "expected leg_hold_cleared audit row");
    assert.ok(!audits.find((a) => a.action === "leg_sop_hold_cleared"), "no sop_hold_cleared for operator-hold path");
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

// --- /reclassify MAS-clear + phase guard (Task #211) ---------------------

test("POST /claims/:id/reclassify clears MAS columns and recomputes group reattest_required", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "cannot_dispute",
    invoiceGroupId: group.id,
  });
  await db.update(claimsTable).set({
    masActionRequired: "cancel",
    dropReason: "cannot_dispute",
    droppedAt: new Date(),
  }).where(eq(claimsTable.id, claim.id));
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/reclassify`, { method: "POST" });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.masActionRequired, null, "masActionRequired must be null after reclassify");
    assert.equal(res.json.masActionCompletedAt, null, "masActionCompletedAt must be null after reclassify");
    assert.equal(res.json.masActionCompletedBy, null, "masActionCompletedBy must be null after reclassify");
    assert.equal(res.json.masActionNote, null, "masActionNote must be null after reclassify");

    const [postGroup] = await db.select().from(invoiceGroupsTable).where(eq(invoiceGroupsTable.id, group.id));
    assert.equal(postGroup.reattestRequired, false, "group reattest_required must recompute to false when only MAS leg is reclassified");

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    const reclAudit = audits.find((a) => a.action === "leg_reclassified");
    assert.ok(reclAudit, "expected leg_reclassified audit row");
    const meta = reclAudit!.metadata as any;
    assert.equal(meta.previousMasActionRequired, "cancel", "audit must record prior masActionRequired");
    assert.equal(meta.previousMasActionCompletedAt, false, "audit must record prior masActionCompletedAt as boolean");
    assert.equal(meta.previousGroupPhase, "response-pending", "audit must record prior group phase");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/reclassify is refused when group is in mas-action-required phase", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  await db.update(invoiceGroupsTable).set({ reattestRequired: true }).where(eq(invoiceGroupsTable.id, group.id));
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "cannot_dispute",
    invoiceGroupId: group.id,
  });
  await db.update(claimsTable).set({
    masActionRequired: "cancel",
    dropReason: "cannot_dispute",
    droppedAt: new Date(),
  }).where(eq(claimsTable.id, claim.id));
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/reclassify`, { method: "POST" });
    assert.equal(res.status, 409);
    assert.equal(res.json.actualState, "mas-action-required");
    assert.ok(res.json.error.includes("admin-correction"), "error message should mention admin-correction flow");

    const [post] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(post.masActionRequired, "cancel", "no column writes should happen on 409");

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    assert.ok(!audits.find((a) => a.action === "leg_reclassified"), "no audit row should be emitted on 409");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/reclassify is refused when group is in closed phase", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Resolved" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "portal_dispute",
    invoiceGroupId: group.id,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/reclassify`, { method: "POST" });
    assert.equal(res.status, 409);
    // Wave C: closed-phase children must carry terminal final_*
    // dispositions per the validate_disposition_against_phase trigger,
    // so the leg sub-status resolves to `frozen` and the leg gate
    // fires before the group-phase gate. The 409 is still produced;
    // only the actualState shape changes.
    assert.equal(res.json.actualState, "frozen");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/reclassify — portal guard still fires when group is in pre-submit but has a submitted submission", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "portal_dispute",
    invoiceGroupId: group.id,
  });
  await db.insert(portalSubmissionsTable).values({
    invoiceGroupId: group.id,
    status: "submitted",
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/reclassify`, { method: "POST" });
    assert.equal(res.status, 409);
    assert.equal(res.json.expectedState, "no_submission", "portal guard should fire (phase guard passes for pre-submit)");
    assert.equal(res.json.actualState, "submission_exists");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/reclassify with no MAS columns set succeeds and audit records null priors", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "portal_dispute",
    invoiceGroupId: group.id,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/reclassify`, { method: "POST" });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.masActionRequired, null);

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    const reclAudit = audits.find((a) => a.action === "leg_reclassified");
    assert.ok(reclAudit, "expected leg_reclassified audit row");
    const meta = reclAudit!.metadata as any;
    assert.equal(meta.previousMasActionRequired, null, "prior masActionRequired should be null");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("POST /claims/:id/reclassify preserves claim_verdict rows (append-only invariant)", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "Needs Review" });
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
    sopOutcome: "dispute",
    invoiceGroupId: group.id,
    status: "Needs Review",
  });
  await db.insert(claimVerdictTable).values({
    claimId: claim.id,
    source: "operator_confirmed",
    outcome: "Denied",
  });
  await db.update(claimsTable).set({ masActionRequired: "cancel" }).where(eq(claimsTable.id, claim.id));
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/reclassify`, { method: "POST" });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);

    const verdicts = await db.select().from(claimVerdictTable).where(eq(claimVerdictTable.claimId, claim.id));
    assert.equal(verdicts.length, 1, "claim_verdict row must still exist after reclassify");
    assert.equal(verdicts[0].outcome, "Denied", "verdict outcome must be preserved");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- Task #232: auto-exclude blank-description siblings on classify-and-promote --------

test("Needs Review → Needs Evidence via group classify auto-excludes blank-description sibling claims", async () => {
  const errType = await createSeedErrorType();
  // The Needs Review → Needs Evidence auto_after_classify path is a
  // triage-phase transition (per `derivePhaseFromLegacy`); override
  // the default fixture mapping (which treats Needs Review as
  // response_received for the response-pending tests) so the deferred
  // disposition phase trigger sees the correct parent phase when
  // excludeLegCore stamps disposition='disposed_nonissue'.
  const group = await createSeedGroup({ status: "Needs Review", phase: "triage" });
  // Qualifying claim — has errorDetails. The classify endpoint will set
  // the group's errorTypeId, which fires auto_after_classify and the
  // sibling-clear hook.
  const qualifying = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  await db.update(claimsTable).set({ errorDetails: "real issue" }).where(eq(claimsTable.id, qualifying.id));
  // Two blank siblings — these should auto-exclude.
  const blank1 = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  const blank2 = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  await db.update(claimsTable)
    .set({ errorDetails: null })
    .where(eq(claimsTable.id, blank1.id));
  await db.update(claimsTable)
    .set({ errorDetails: "   " })
    .where(eq(claimsTable.id, blank2.id));

  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}`, {
      method: "PATCH",
      body: { errorTypeId: String(errType.id) },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.status, "Needs Evidence", "group must auto-advance to Needs Evidence");

    const blanks = await db.select().from(claimsTable).where(inArray(claimsTable.id, [blank1.id, blank2.id]));
    for (const b of blanks) {
      assert.equal(b.includedInDispute, false, `blank sibling ${b.id} must be auto-excluded`);
    }

    const stillIn = await db.select().from(claimsTable).where(eq(claimsTable.id, qualifying.id));
    assert.equal(stillIn[0].includedInDispute, true, "qualifying claim must remain in dispute");

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.invoiceGroupId, group.id));
    type LegExcludedMeta = { source?: string; reason?: string } | null;
    const autoAudits = audits.filter(
      (a) => (a.metadata as LegExcludedMeta)?.source === "auto_after_classify_sibling_clear",
    );
    assert.equal(autoAudits.length, 2, `expected two leg_excluded audits with source=auto_after_classify_sibling_clear; got ${autoAudits.length}`);
    for (const a of autoAudits) {
      assert.equal(a.action, "leg_excluded");
      assert.equal((a.metadata as LegExcludedMeta)?.reason, "non_issue");
    }
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

test("Needs Review → Needs Evidence is a no-op for the sibling-clear hook when every leg is blank", async () => {
  const errType = await createSeedErrorType();
  // See sibling test above re: Needs Review → Needs Evidence triage override.
  const group = await createSeedGroup({ status: "Needs Review", phase: "triage" });
  const a = await createSeedClaim({ invoiceGroupId: group.id, errorTypeId: null });
  const b = await createSeedClaim({ invoiceGroupId: group.id, errorTypeId: null });
  await db.update(claimsTable).set({ errorDetails: null }).where(inArray(claimsTable.id, [a.id, b.id]));

  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}`, {
      method: "PATCH",
      body: { errorTypeId: String(errType.id) },
    });
    assert.equal(res.status, 200);
    const rows = await db.select().from(claimsTable).where(inArray(claimsTable.id, [a.id, b.id]));
    for (const r of rows) {
      assert.equal(r.includedInDispute, true, `leg ${r.id} must NOT be auto-excluded when every sibling is blank`);
    }
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- Safety net: closing a group auto-excludes still-unclassified included legs ---

test("closing a group (Resolved) auto-excludes any still-unclassified included legs", async () => {
  const group = await createSeedGroup({ status: "New" });
  const stranded1 = await createSeedClaim({ invoiceGroupId: group.id, errorTypeId: null });
  const stranded2 = await createSeedClaim({ invoiceGroupId: group.id, errorTypeId: null });
  await db.update(claimsTable).set({ errorDetails: "blank-ish" }).where(eq(claimsTable.id, stranded1.id));
  await db.update(claimsTable).set({ errorDetails: null }).where(eq(claimsTable.id, stranded2.id));

  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/status`, {
      method: "PATCH",
      body: { status: "Resolved", reason: "Closed without classification" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);

    const rows = await db.select().from(claimsTable).where(inArray(claimsTable.id, [stranded1.id, stranded2.id]));
    for (const r of rows) {
      assert.equal(r.includedInDispute, false, `leg ${r.id} must be auto-excluded when group closes`);
    }

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.invoiceGroupId, group.id));
    type Meta = { source?: string; reason?: string } | null;
    const autoAudits = audits.filter((a) => {
      const src = (a.metadata as Meta)?.source ?? "";
      return src.startsWith("auto_on_terminal_close:");
    });
    assert.equal(autoAudits.length, 2, `expected two leg_excluded audits with source=auto_on_terminal_close:*; got ${autoAudits.length}`);
    for (const a of autoAudits) {
      assert.equal(a.action, "leg_excluded");
      assert.equal((a.metadata as Meta)?.reason, "non_issue");
    }
  } finally {
    await cleanupGroup(group.id);
  }
});

test("closing a group leaves already-classified legs alone", async () => {
  const errType = await createSeedErrorType();
  const group = await createSeedGroup({ status: "New" });
  const classified = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
  });

  try {
    const res = await fetchJson(`/api/invoice-groups/${group.id}/status`, {
      method: "PATCH",
      body: { status: "Resolved", reason: "Closed after work done" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);

    const [row] = await db.select().from(claimsTable).where(eq(claimsTable.id, classified.id));
    assert.equal(row.includedInDispute, true, "classified leg must remain in dispute after group close");
  } finally {
    await cleanupGroup(group.id);
    await cleanupErrorType(errType.id);
  }
});

// --- Task #232: extended LEG_EXCLUSION_REASONS accepts non_issue and cannot_dispute ---

test("POST /claims/:id/exclude accepts reason=non_issue", async () => {
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "non_issue" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, false);
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("POST /claims/:id/exclude accepts reason=cannot_dispute", async () => {
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "cannot_dispute" },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, false);
  } finally {
    await cleanupClaim(claim.id);
  }
});

// --- Task #689: handled_offline reason path -----------------------------

test("POST /claims/:id/exclude rejects reason=handled_offline without a note", async () => {
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline" },
    });
    assert.equal(res.status, 400, `expected 400, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.match(String(res.json.error ?? ""), /handled_offline/);
    // Leg must NOT have been excluded.
    const [row] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(row.includedInDispute, true);
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("POST /claims/:id/exclude rejects reason=handled_offline when trimmed note is shorter than 10 chars", async () => {
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline", note: "   short   " },
    });
    assert.equal(res.status, 400, `expected 400, got ${res.status} (${JSON.stringify(res.json)})`);
    const [row] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(row.includedInDispute, true);
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("POST /claims/:id/exclude with reason=handled_offline excludes the leg and emits claim_removed_handled_offline audit", async () => {
  const claim = await createSeedClaim({ errorTypeId: null });
  try {
    const note = "Confirmed in MAS portal — already paid offline last week.";
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline", note },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, false);

    const audits = await db
      .select()
      .from(auditLogsTable)
      .where(eq(auditLogsTable.claimId, claim.id));
    const handledOffline = audits.find((a) => a.action === "claim_removed_handled_offline");
    assert.ok(handledOffline, `expected claim_removed_handled_offline audit row; got actions ${audits.map((a) => a.action).join(", ")}`);
    assert.equal(
      audits.find((a) => a.action === "leg_excluded"),
      undefined,
      "must NOT also emit the generic leg_excluded action — the handled_offline path replaces it",
    );
    type Meta = { reason?: string; note?: string; source?: string } | null;
    const meta = handledOffline!.metadata as Meta;
    assert.equal(meta?.reason, "handled_offline");
    assert.equal(meta?.note, note);
    assert.equal(meta?.source, "manual");
    assert.match(String(handledOffline!.details ?? ""), /Removed — handled offline/);
  } finally {
    await cleanupClaim(claim.id);
  }
});

test("POST /claims/:id/exclude with reason=handled_offline succeeds from `investigating` and clears classification", async () => {
  // 2026-05-14 — the source-state guard was widened from
  // `needs_classification` only to {needs_classification, investigating}
  // so operators can pull a classified-but-unwalked leg out of the
  // dispute (e.g. they realised mid-walk that the leg was already
  // handled offline). This test pins that handled_offline reuses the
  // same widened guard and that the classification fields are cleared
  // as part of the exclusion. The "still 409 from beyond investigating"
  // safety net is covered by a separate `sub-status excluded` test
  // earlier in the file.
  const errType = await createSeedErrorType();
  const claim = await createSeedClaim({
    errorTypeId: String(errType.id),
    errorTypeName: errType.name,
  });
  try {
    const res = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline", note: "Already attested offline last week." },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, false);
    assert.equal(res.json.errorTypeId, null, "errorTypeId must be cleared");
    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    assert.ok(
      audits.find((a) => a.action === "claim_removed_handled_offline"),
      "expected claim_removed_handled_offline audit row (handled_offline keeps its distinct action)",
    );
  } finally {
    await cleanupClaim(claim.id);
    await cleanupErrorType(errType.id);
  }
});

// --- Task #694: undo handled_offline path -------------------------------

test("POST /claims/:id/include with undoHandledOffline rejects when note is missing", async () => {
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  try {
    const exitNote = "Already attested in MAS portal — refund posted.";
    const exit = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline", note: exitNote },
    });
    assert.equal(exit.status, 200);

    const res = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: { undoHandledOffline: true },
    });
    assert.equal(res.status, 400, `expected 400, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.match(String(res.json.error ?? ""), /note required/);
    // Leg must remain excluded.
    const [row] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(row.includedInDispute, false);
  } finally {
    await cleanupGroup(group.id);
  }
});

test("POST /claims/:id/include with undoHandledOffline rejects when trimmed note is shorter than 10 chars", async () => {
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  try {
    const exit = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline", note: "Already attested in MAS portal — refund posted." },
    });
    assert.equal(exit.status, 200);

    const res = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: { undoHandledOffline: true, note: "   short   " },
    });
    assert.equal(res.status, 400, `expected 400, got ${res.status} (${JSON.stringify(res.json)})`);
    const [row] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(row.includedInDispute, false);
  } finally {
    await cleanupGroup(group.id);
  }
});

test("POST /claims/:id/include with undoHandledOffline rejects when last exit was not handled_offline (409)", async () => {
  // Excluded via the legacy `clean_leg` reason — the undo path must
  // refuse so the audit trail can't be retro-fitted into a
  // handled-offline reversal.
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  try {
    const exit = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "clean_leg" },
    });
    assert.equal(exit.status, 200);

    const res = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: { undoHandledOffline: true, note: "Trying to undo via wrong path here." },
    });
    assert.equal(res.status, 409, `expected 409, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.expectedState, "claim_removed_handled_offline");
    assert.equal(res.json.actualState, "leg_excluded");
    const [row] = await db.select().from(claimsTable).where(eq(claimsTable.id, claim.id));
    assert.equal(row.includedInDispute, false);
  } finally {
    await cleanupGroup(group.id);
  }
});

test("POST /claims/:id/include with undoHandledOffline restores the leg and emits claim_removed_handled_offline_undone audit", async () => {
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  try {
    const exitNote = "Already attested in MAS portal — refund posted.";
    const exit = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline", note: exitNote },
    });
    assert.equal(exit.status, 200);

    const undoNote = "Refund was reversed — re-opening dispute path.";
    const res = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: { undoHandledOffline: true, note: undoNote },
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, true);

    // Sub-status should snap back to needs_classification (the only
    // state from which handled_offline could have been entered).
    assert.equal(res.json.errorTypeId, null);

    const audits = await db
      .select()
      .from(auditLogsTable)
      .where(and(
        eq(auditLogsTable.claimId, claim.id),
        inArray(auditLogsTable.action, [
          "claim_removed_handled_offline",
          "claim_removed_handled_offline_undone",
          "leg_included",
        ]),
      ))
      .orderBy(desc(auditLogsTable.timestamp));
    const undone = audits.find((a) => a.action === "claim_removed_handled_offline_undone");
    assert.ok(undone, `expected claim_removed_handled_offline_undone audit row; got actions ${audits.map((a) => a.action).join(", ")}`);
    assert.equal(
      audits.find((a) => a.action === "leg_included"),
      undefined,
      "must NOT also emit the generic leg_included action — the undo path replaces it",
    );
    type Meta = { note?: string; previousSubStatus?: string; undoHandledOffline?: boolean } | null;
    const meta = undone!.metadata as Meta;
    assert.equal(meta?.note, undoNote);
    assert.equal(meta?.previousSubStatus, "excluded");
    assert.equal(meta?.undoHandledOffline, true);
    assert.match(String(undone!.details ?? ""), /Undone — re-included after handled-offline removal/);
  } finally {
    await cleanupGroup(group.id);
  }
});

test("POST /claims/:id/include with undoHandledOffline rejects a second consecutive undo (409)", async () => {
  // After a successful undo, the most recent exit-class audit row is
  // `claim_removed_handled_offline_undone` (or — once the leg is
  // re-excluded — a different reason). Either way, a fresh undo must
  // not piggy-back on the original handled-offline entry.
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  try {
    const exit = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline", note: "Already attested in MAS portal — refund posted." },
    });
    assert.equal(exit.status, 200);

    const undo1 = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: { undoHandledOffline: true, note: "Refund reversed — re-opening dispute." },
    });
    assert.equal(undo1.status, 200);

    // Re-exclude with the legacy reason to leave the leg excluded
    // again, then attempt a second undo. The latest exit row is now
    // `leg_excluded`, so the gate must reject.
    const reExclude = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "clean_leg" },
    });
    assert.equal(reExclude.status, 200);

    const undo2 = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: { undoHandledOffline: true, note: "Second undo attempt that must be refused." },
    });
    assert.equal(undo2.status, 409, `expected 409, got ${undo2.status} (${JSON.stringify(undo2.json)})`);
    assert.equal(undo2.json.expectedState, "claim_removed_handled_offline");
    assert.equal(undo2.json.actualState, "leg_excluded");
  } finally {
    await cleanupGroup(group.id);
  }
});

test("POST /claims/:id/include without undoHandledOffline still uses the legacy leg_included path", async () => {
  // Even when the leg was originally excluded via handled_offline,
  // a plain re-include (no flag) keeps the existing behaviour: no
  // note required and the audit row is `leg_included`. This protects
  // older clients that haven't picked up the new payload yet.
  const group = await createSeedGroup({ status: "Needs Evidence" });
  const claim = await createSeedClaim({
    invoiceGroupId: group.id,
    errorTypeId: null,
  });
  try {
    const exit = await fetchJson(`/api/claims/${claim.id}/exclude`, {
      method: "POST",
      body: { reason: "handled_offline", note: "Already attested in MAS portal — refund posted." },
    });
    assert.equal(exit.status, 200);

    const res = await fetchJson(`/api/claims/${claim.id}/include`, {
      method: "POST",
      body: {},
    });
    assert.equal(res.status, 200, `expected 200, got ${res.status} (${JSON.stringify(res.json)})`);
    assert.equal(res.json.includedInDispute, true);

    const audits = await db.select().from(auditLogsTable).where(eq(auditLogsTable.claimId, claim.id));
    assert.ok(audits.find((a) => a.action === "leg_included"), "expected legacy leg_included audit row");
    assert.equal(
      audits.find((a) => a.action === "claim_removed_handled_offline_undone"),
      undefined,
      "must NOT emit the undo-specific action when the flag is absent",
    );
  } finally {
    await cleanupGroup(group.id);
  }
});
