export const AUDIT_ACTION_NAMES = [
  "status_changed",
  "outcome_changed",
  "status_and_outcome_changed",
  "claim_status_changed",
  "claim_outcome_changed",
  "group_status_changed",
  "group_outcome_changed",
  "group_status_and_outcome_changed",
  "leg_excluded",
  "leg_included",
  "leg_concluded",
  "leg_sop_advanced",
  "leg_classified",
  "leg_sop_hold_cleared",
  "group_sop_advanced_bulk",
  "group_triaged",
  "group_resolved",
  "group_denied",
  "group_held",
  "group_hold_removed",
  "group_edited",
  "group_deleted",
  "group_evidence_added",
  "group_evidence_removed",
  "group_workflow_step",
  "group_error_type_assigned",
  "group_invoice_number_renamed",
  "group_reattest_queued_bulk",
  "claim_created",
  "claim_deleted",
  "claim_edited",
  "claims_imported",
  "evidence_updated",
  "error_type_assigned",
  "closure_addressed",
  "closure_review_state_changed",
  "closure_review_updated",
  "closure_evidence_attached",
  "attestation_self_confirmed",
  "attestation_queued",
  "attestation_queue_confirmed",
  "attestation_completed",
  "mas_reattest_recorded_offline",
  "mas_reattest_completed",
  "mas_action_completed",
  "hold_placed",
  "hold_removed",
  "workflow_updated",
  "submission_retry_scheduled",
  "submission_retries_exhausted",
  "submission_stuck_reset",
  "stuck_reset",
  "submission_manual_requeue",
  "submission_actor_bypass",
  "submission_complete",
  "portal_understanding_preflight",
  "portal_draft_created",
  "portal_draft_edited",
  "portal_draft_regenerated",
  "portal_draft_reverted",
  "portal_submission_submitted",
  "portal_submission_confirmed",
  "portal_submission_cancelled",
  "lint_warnings_bypassed",
  "response_reassigned",
  "response_unmatched",
  "response_tagged",
  "response_received",
  "outbound_sent",
  "email_generated",
  "email_reply_sent",
  "bounce_received",
  "payor_denial_reason_recorded",
  "awaiting_payor_again",
  "connector_unhealthy",
  "notification_opt_out_changed",
  "note_added",
  "note_deleted",
  "batch_claimed",
  "batch_failed",
  "dry_run_complete",
  "sandbox_run_complete",
  "sandbox_run_failed",
] as const;

export type AuditActionName = (typeof AUDIT_ACTION_NAMES)[number];

const ACTION_SET: ReadonlySet<string> = new Set(AUDIT_ACTION_NAMES);

export function isAuditActionName(value: string): value is AuditActionName {
  return ACTION_SET.has(value);
}
