// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tree-editor/NodeCanvas.tsx": () => import("../components/mockups/tree-editor/NodeCanvas.tsx"),
  "./components/mockups/tree-editor/RailPanel.tsx": () => import("../components/mockups/tree-editor/RailPanel.tsx"),
  "./components/mockups/tree-editor/VerticalFlow.tsx": () => import("../components/mockups/tree-editor/VerticalFlow.tsx")
};
