-- Portal orphan re-link backfill (generated 2026-05-21T09:12:17.534Z).
-- Generated by artifacts/api-server/src/scripts/backfill-orphan-portal-tickets.ts
-- Re-running this script is safe: the NOT EXISTS guard makes the
-- INSERT idempotent on (invoice_number, portal_ticket_id).
-- Sibling rows are pinned by portal_submissions.id (the row the
-- classifier picked as the most-recent sibling by submitted_at),
-- so the clone is deterministic even when multiple rows share the
-- same sibling portal_ticket_id on an invoice.

-- No orphan-with-sibling rows to backfill.
